//Action
const ACTION = {
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
  RESET_SEARCH_TERM: "RESET_SEARCH_TERM",
  SET_NOTIFICATION_MESSAGE: "SET_NOTIFICATION_MESSAGE",
  RESET_NOTIFICATION_MESSAGE: "RESET_NOTIFICATION_MESSAGE",
};

export { ACTION };
