//Action
const ACTION = {
  SHOW_SIGNUP_FORM: "SHOW_SIGNUP_FORM",
  HIDE_SIGNUP_FORM: "HIDE_SIGNUP_FORM",
  SHOW_PLAYER: "SHOW_PLAYER",
  HIDE_PLAYER: "HIDE_PLAYER",
  TOGGLE_SIGNUP_FORM: "TOGGLE_SIGNUP_FORM",
  SET_SEARCH_TERM: "SET_SEARCH_TERM",
};

export {ACTION};
